IF NOT DEFINED MTCLSH (set MTCLSH=G:/MTCLSH/mtclsh.bat)
IF NOT DEFINED MTCLSH_HOME (set MTCLSH_HOME=G:/MTCLSH/mtclsh_85)
IF NOT DEFINED SVN_HOME (set SVN_HOME=C:/Program Files/TortoiseSVN)
IF NOT DEFINED SVN_APP (set SVN_APP=C:/Program Files/TortoiseSVN/bin/svn.exe)
IF NOT DEFINED SVN_LOCAL (set SVN_LOCAL=C:/svn_local)
IF NOT DEFINED SVN_URL (set SVN_URL=https://10.157.201.148:18080/svn)
IF NOT DEFINED NSIS_APP (set NSIS_APP=C:/Program Files/NSIS/makeNSIS.exe)
IF NOT DEFINED NSIS_HOME (set NSIS_HOME=C:/Program Files/NSIS)
IF NOT DEFINED TCLSH_HOME (set TCLSH_HOME=C:/opt/Tcl)
IF NOT DEFINED TCLSH (set TCLSH=C:/opt/Tcl/bin/tclsh.exe)
IF NOT DEFINED TCL_LIBRARY (set TCL_LIBRARY=C:/opt/Tcl/lib)
IF NOT DEFINED 7ZIP_HOME (set 7ZIP_HOME=C:/Program Files/7-Zip)
IF NOT DEFINED 7ZIP_APP (set 7ZIP_APP=C:/Program Files/7-Zip/7z.exe)
IF NOT DEFINED ORACLE_HOME11 (set ORACLE_HOME11=C:/oracle/product/11.2.0/client_1)
IF NOT DEFINED SQLPLUS_EXE (set SQLPLUS_EXE=C:/oracle/product/11.2.0/client_1/BIN/sqlplus)
IF NOT DEFINED IMPDP11 (set IMPDP11=C:/oracle/product/11.2.0/client_1/BIN/impdp.exe)
IF NOT DEFINED EXPDP11 (set EXPDP11=C:/oracle/product/11.2.0/client_1/BIN/expdp.exe)
IF NOT DEFINED ORACLE_HOME10 (set ORACLE_HOME10=C:/oracle/product/10.2.0/client_1)
IF NOT DEFINED SQLPLUS10 (set SQLPLUS10=C:/oracle/product/10.2.0/client_1/BIN/sqlplus)
IF NOT DEFINED IMPDP10 (set IMPDP10=C:/oracle/product/10.2.0/client_1/BIN/impdp.exe)
IF NOT DEFINED EXPDP10 (set EXPDP10=C:/oracle/product/10.2.0/client_1/BIN/expdp.exe)
IF NOT DEFINED SQLPLUSXE (set SQLPLUSXE=C:/oraclexe/app/oracle/product/11.2.0/server/bin/sqlplus)
IF NOT DEFINED IMPDPXE (set IMPDPXE=C:/oraclexe/app/oracle/product/11.2.0/server/bin/impdp.exe)
IF NOT DEFINED EXPDPXE (set EXPDPXE=C:/oraclexe/app/oracle/product/11.2.0/server/bin/expdp.exe)
IF NOT DEFINED ORACLE_HOMEXE (set ORACLE_HOMEXE=C:/oraclexe/app/oracle/product/11.2.0/server)
IF NOT DEFINED JAVA_HOME6 (set JAVA_HOME6=C:/Program Files/Java/jdk1.6.0_45)
IF NOT DEFINED JAVA_HOME7 (set JAVA_HOME7=C:/Program Files/Java/jdk1.7.0_79)
IF NOT DEFINED JAVA_HOME8 (set JAVA_HOME8=C:/Program Files/Java/jdk1.8.0_65)
IF NOT DEFINED TOMCAT_HOME6 (set TOMCAT_HOME6=C:/Tomcat6)
IF NOT DEFINED TOMCAT_HOME7 (set TOMCAT_HOME7=C:/opt/Tomcat/Tomcat7)
IF NOT DEFINED TOMCAT_HOME8 (set TOMCAT_HOME8=C:/opt/Tomcat/Tomcat8)
IF NOT DEFINED GIT_RE_URL (set GIT_RE_URL=http://cic-svr-atlassian/bitbucket/scm/re)
IF NOT DEFINED GIT_LOCAL (set GIT_LOCAL=C:/git_local)
IF NOT DEFINED GIT_EXE (set GIT_EXE=C:/opt/git/git-cmd.exe)



