set env_vars {
MTCLSH          "G:/MTCLSH/mtclsh.bat"
MTCLSH_HOME     "G:/MTCLSH/mtclsh_85"
SVN_HOME        "C:/Program Files/TortoiseSVN"
SVN_APP         "C:/Program Files/TortoiseSVN/bin/svn.exe"
SVN_LOCAL       "C:/svn_local"
SVN_URL         "https://10.157.201.148:18080/svn"
NSIS_APP        "C:/Program Files/NSIS/makeNSIS.exe"
NSIS_HOME       "C:/Program Files/NSIS"
TCLSH_HOME      "C:/opt/Tcl"
TCLSH           "C:/opt/Tcl/bin/tclsh.exe"
TCL_LIBRARY     "C:/opt/Tcl/lib"
7ZIP_HOME       "C:/Program Files/7-Zip"
7ZIP_APP        "C:/Program Files/7-Zip/7z.exe"
ORACLE_HOME11   "C:/oracle/product/11.2.0/client_1"
SQLPLUS_EXE     "C:/oracle/product/11.2.0/client_1/BIN/sqlplus"
IMPDP11         "C:/oracle/product/11.2.0/client_1/BIN/impdp.exe"
EXPDP11         "C:/oracle/product/11.2.0/client_1/BIN/expdp.exe"
ORACLE_HOME10   "C:/oracle/product/10.2.0/client_1"
SQLPLUS10       "C:/oracle/product/10.2.0/client_1/BIN/sqlplus"
IMPDP10         "C:/oracle/product/10.2.0/client_1/BIN/impdp.exe"
EXPDP10         "C:/oracle/product/10.2.0/client_1/BIN/expdp.exe"
SQLPLUSXE       "C:/oraclexe/app/oracle/product/11.2.0/server/bin/sqlplus"
IMPDPXE         "C:/oraclexe/app/oracle/product/11.2.0/server/bin/impdp.exe"
EXPDPXE         "C:/oraclexe/app/oracle/product/11.2.0/server/bin/expdp.exe"
ORACLE_HOMEXE   "C:/oraclexe/app/oracle/product/11.2.0/server"
JAVA_HOME6      "C:/Program Files/Java/jdk1.6.0_45"
JAVA_HOME7      "C:/Program Files/Java/jdk1.7.0_79"
JAVA_HOME8      "C:/Program Files/Java/jdk1.8.0_65"
TOMCAT_HOME6    "C:/Tomcat6"
TOMCAT_HOME7    "C:/opt/Tomcat/Tomcat7"
TOMCAT_HOME8    "C:/opt/Tomcat/Tomcat8"
GIT_EXE 		"C:/opt/git/git-cmd.exe"
GIT_LOCAL 		"C:/git_local"
GIT_RE_URL 		"http://cic-svr-atlassian/bitbucket/scm/re"
}

